### ISSUE TITLE
program isnt ran on linux

### ISSUE THREAD

**Issue by Ianyourgod** [AdoHTQ/Batpu2-VM#13]
The program is not getting run.
I drag in the .as file, click run, and nothing happens, besides a carrot appearing by line 1. The step button doesnt do anything at all.

I am on ubuntu 22.04.

**Comment by Trynera** [comment]
I mean it works fine for me on windows, but when I try running it in godot, I get the same issue (also the display doesn't appear? This isn't the fault of my commits btw cuz when I ran godot on my fork with the optimizations and without the other stuff ado merged, it worked perfectly fine!

**Comment by Trynera** [comment]
I wanna recomment on the comment above me. It somehow works for me now??? Idk what changed but it works now for me so it's fine ig (other than for Linux??)

**Comment by Trynera** [comment]
@Ianyourgod I recommend you press the reset button, if that doesn't fix it then the issue were 2 seperate problems. If it does fix it then the fix to this should be really simple

**Comment by AdoHTQ** [comment]
Is there a command that refers to python 3 on both Windows and Linux? I think my PATH is messed up because running py works but python and python3 both open the windows store.

**Comment by AdoHTQ** [comment]
This is fixed in the new release by switching the command back to "python" and conditionally changing to "python3" if on linux
