### ISSUE TITLE
Step function broken!!!

### ISSUE THREAD

**Issue by Trynera** [AdoHTQ/Batpu2-VM#14]
the Step function doesn't update visuals which breaks the entirety of that button. The solution is really easy, go into main.cs and replace the step function with the following:
```cs
private void Step()
{
	if (bytecode == null) return;
	if (!paused) StartStop();
	RunNextInstruction();
	assemblyView.follow = true;
	UpdateVisualisers();
}
```

**Comment by AdoHTQ** [comment]
Fixed
