### ISSUE TITLE
ctrl-s on linux just writes s

### ISSUE THREAD

**Issue by Ianyourgod** [AdoHTQ/Batpu2-VM#22]
Using ctrl+s in the code editor just writes an s. it does not reassemble.
I am on ubuntu 22.04

**Comment by AdoHTQ** [comment]
I'm not sure why this happens, but f5 also reassembles so you can just use that.

**Comment by KilianVounckx** [comment]
I'm on Pop!OS. When the text editor is not focused, ctrl+s works. When the editor is in focus, ctrl+s writes an s. Maybe this helps.

**Comment by AdoHTQ** [comment]
If this is a reccurring issue on Linux, then I'll check it out on my Fedora install. Not sure why it would be OS dependent though.

**Comment by KilianVounckx** [comment]
Pop!OS is built on top of Ubuntu as far as I know, so might be just an Ubuntu thing

**Comment by olvior** [comment]
I'm on ubuntu and have the same issue.

**Comment by olvior** [comment]
I found the same issue and the solution here: https://github.com/godotengine/godot/issues/88768
