### ISSUE TITLE
Setting execution rate to high speeds skips parts of code

### ISSUE THREAD

**Issue by saaawdust** [AdoHTQ/Batpu2-VM#24]
If you set your execution rate to a high number, such as 1000, parts of the code seem to be skipped.
Here's an example with a piece of code that individually draws each pixel of a space invader when the execution rate is 100:
![image](https://github.com/user-attachments/assets/e49851f3-ce45-453b-842b-1f2e4f9448de)
It works perfectly fine.
Now the same code, again, but the execution rate is 1000:
![image](https://github.com/user-attachments/assets/2cf9e3dc-b3ee-4ff4-ae08-a2e07897561d)
You can see the top part of the render has started to disappear.
Finally, I set the execution rate to 10000:
![image](https://github.com/user-attachments/assets/3e58f251-7935-4061-b467-0f9daac0c882)
The entire code is skipped. The higher the execution rate seems to be, the more code it skips - and this doesn't only happen with rendering, I've had this issue everywhere!

Reproduction Steps:

If it helps, I'm on windows!
Paste this very large and inefficient chuck of code: https://pastebin.com/xV57PTmm
This is just an example.

**Comment by saaawdust** [comment]
Looking at this more: For me atleast, this seems to happen SPECIFICALLY when the execution rate is above 700.
![image](https://github.com/user-attachments/assets/5591c2db-e95c-4a7e-ac2c-2894b13559f5)
![image](https://github.com/user-attachments/assets/f122b28a-958f-40d0-9a03-77f14e01c192)

**Comment by AdoHTQ** [comment]
If you are in Matt's discord, could you try running some of the programs in the #cpu-programs channel. People have run programs at tens of thousands of instructions per second with no issues.

**Comment by saaawdust** [comment]
Interesting that these programs work - Do you think it's possibly to do something with the way I programmed it? (Since it doesn't use any loops as of?)

**Comment by AdoHTQ** [comment]
Just looked at your code. I'm pretty sure it goes over the instruction limit of 1024. Not sure why execution speed would affect this though.

**Comment by Noname-Official** [comment]
In the beginning you JMP to .main but after you use RET. Changing this to a HLT fixes it.

**Comment by Noname-Official** [comment]
In the beginning, you JMP to .main but after you use RET. Changing this to a HLT fixes it.
