### ISSUE TITLE
Inverted inputs

### ISSUE THREAD

**Issue by Thesuper997** [AdoHTQ/Batpu2-VM#3]

**Comment by AdoHTQ** [comment]
Are the inputs inverted just on the visualizer, or is it in a program too?

**Comment by Thesuper997** [comment]
I don't know. I need a test program to be sure...

**Comment by AdoHTQ** [comment]
[input.txt](https://github.com/user-attachments/files/15923335/input.txt)
Using this test program, I have determined that the inputs seem to be logically inverted too. The result when pressing the A button (K key) was 16 in r1 when it should be 32.

**Comment by AdoHTQ** [comment]
This is fixed in the 2.1 release.

**Comment by Thesuper997** [comment]
nice
