### ISSUE TITLE
behavior of instruction "brh ge" inconsistent

### ISSUE THREAD

**Issue by erinsc** [AdoHTQ/Batpu2-VM#4]
the instruction "brh ge" is meant to take the branch when the "Carry" flag is set, however it only takes it when "Carry" is set and "Zero" is cleared. "brh le" does the opposite, taking branch for all flag states except when "Carry" is set and "Zero" is not. Code used to produce all 4 possible flag states:
```c
       ldi r1 1
       adi r1 255
       brh ge .good
.bad   hlt
.good  hlt
```
Where constants 1 and 255 have been replaced to produce all 4 possible states of flags.
```cpp
1 + 0   = 1 -> Both flags cleared,    branch not taken
0 + 0   = 0 -> Zero set, Carry clear, branch not taken
2 + 255 = 1 -> Zero clear, Carry set, branch taken
1 + 255 = 0 -> Both flags set,        branch not taken <- Incorrect behavior
```
My guess is this happened because the behavior was modeled off of the instruction "cmp", where its not possible to set both flags at once, so the case wasn't accounted for.

**Comment by AdoHTQ** [comment]
This is fixed in the next patch
