### ISSUE TITLE
literal numbers in editor can only be integers

### ISSUE THREAD

**Issue by E1thanz** [AdoHTQ/Batpu2-VM#6]
it'd be nice if you could do for example
LDI r14 0b1000
or
LDI r14 0xAF02
these are just 2 examples but yeah rn you can only put integers (base 10) which is a bummer for if you wanna do bit stuff

**Comment by AdoHTQ** [comment]
This seems like an assembler issue. Submit it here https://github.com/mattbatwings/newcpu
